/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Address {
    apartment?: string;

    block?: string;

    country?: string;

    county?: string;

    entrance?: string;

    floor?: string;

    id?: number;

    latitude?: number;

    longitude?: number;

    number?: string;

    postalCode?: string;

    sector?: string;

    street?: string;

    town?: string;

}
