/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Education {
    degree?: string;

    endDate?: Date;

    id?: number;

    name?: string;

    schoolLocation?: string;

    schoolTitle?: string;

    startDate?: Date;

}
