/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Skill } from './Skill';

export interface Internship {
    active?: boolean;

    deadline?: Date;

    description?: string;

    employmentType?: InternshipEnums.EmploymentTypeEnum;

    endDate?: Date;

    freeSpots?: number;

    id?: number;

    startDate?: Date;

    status?: InternshipEnums.StatusEnum;

    title?: string;

}
export namespace InternshipEnums {
    export enum EmploymentTypeEnum {
        FULLTIME = <any> 'FULL_TIME',
        PARTTIME = <any> 'PART_TIME'
    }
    export enum StatusEnum {
        ACTIVE = <any> 'ACTIVE',
        ENDED = <any> 'ENDED',
        COMING = <any> 'COMING'
    }
}

export interface JoinCompany {
    idInternship?: number;
    idCompany?: number;
}

export interface JoinSkill {
    idInternship?: number;
    skills?: Skill[];
}
