/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';


export enum IntershipStatusRequestStringEnum {
  ACCEPTED = <any> 'ACCEPTED',
  PENDING = <any> 'PENDING',
  REJECTED = <any> 'REJECTED'
}

