/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Internship {
    active?: boolean;

    deadline?: Date;

    description?: string;

    employmentType?: Internship.EmploymentTypeEnum;

    endDate?: Date;

    freeSpots?: number;

    id?: number;

    startDate?: Date;

    status?: Internship.StatusEnum;

    title?: string;

}
export namespace Internship {
    export enum EmploymentTypeEnum {
        FULLTIME = <any> 'FULL_TIME',
        PARTTIME = <any> 'PART_TIME'
    }
    export enum StatusEnum {
        ACTIVE = <any> 'ACTIVE',
        ENDED = <any> 'ENDED',
        COMING = <any> 'COMING'
    }
}
